export const countriesName: string[] = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Republic of)",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (North)",
  "Korea (South)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Minor Outlying Islands (US)",
  "Moldova (Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine (State)",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (US)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const languagesName: string[] = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari Languages",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Central Khmer",
  "Chamorro",
  "Chechen",
  "Chichewa, Chewa, Nyanja",
  "Chinese",
  "Church Slavonic",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Dhivehi, Maldivian",
  "Dutch, Flemish",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Farsi",
  "Fijian",
  "Finnish",
  "French",
  "Fulah",
  "Gaelic",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Gikuyu",
  "Greek",
  "Guarani",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Interlingue, Occidental",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kalaallisut, Greenlandic",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kinyarwanda",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Kwanyama",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Letzeburgesch",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo",
  "Ndonga",
  "Nepali",
  "North Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmal",
  "Norwegian Nynorsk",
  "Nuosu, Sichuan Yi",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Ossetian",
  "Pali",
  "Pashto",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Quechua",
  "Romanian, Moldovan",
  "Romansh",
  "Rundi",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho",
  "South Ndebele",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Valencian, Catalan",
  "Venda",
  "Vietnamese",
  "Volapuk",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
  "Zulu",
];

export const genres: string[] = [
  "PODCASTSERIES_ARTS",
  "PODCASTSERIES_ARTS_BOOKS",
  "PODCASTSERIES_ARTS_DESIGN",
  "PODCASTSERIES_ARTS_FASHION_AND_BEAUTY",
  "PODCASTSERIES_ARTS_FOOD",
  "PODCASTSERIES_ARTS_PERFORMING_ARTS",
  "PODCASTSERIES_ARTS_VISUAL_ARTS",
  "PODCASTSERIES_BUSINESS",
  "PODCASTSERIES_BUSINESS_CAREERS",
  "PODCASTSERIES_BUSINESS_ENTREPRENEURSHIP",
  "PODCASTSERIES_BUSINESS_INVESTING",
  "PODCASTSERIES_BUSINESS_MANAGEMENT",
  "PODCASTSERIES_BUSINESS_MARKETING",
  "PODCASTSERIES_BUSINESS_NON_PROFIT",
  "PODCASTSERIES_COMEDY",
  "PODCASTSERIES_COMEDY_INTERVIEWS",
  "PODCASTSERIES_COMEDY_IMPROV",
  "PODCASTSERIES_COMEDY_STANDUP",
  "PODCASTSERIES_EDUCATION",
  "PODCASTSERIES_EDUCATION_COURSES",
  "PODCASTSERIES_EDUCATION_HOW_TO",
  "PODCASTSERIES_EDUCATION_LANGUAGE_LEARNING",
  "PODCASTSERIES_EDUCATION_SELF_IMPROVEMENT",
  "PODCASTSERIES_FICTION",
  "PODCASTSERIES_FICTION_COMEDY_FICTION",
  "PODCASTSERIES_FICTION_DRAMA",
  "PODCASTSERIES_FICTION_SCIENCE_FICTION",
  "PODCASTSERIES_GOVERNMENT",
  "PODCASTSERIES_HISTORY",
  "PODCASTSERIES_HEALTH_AND_FITNESS",
  "PODCASTSERIES_HEALTH_AND_FITNESS_ALTERNATIVE_HEALTH",
  "PODCASTSERIES_HEALTH_AND_FITNESS_FITNESS",
  "PODCASTSERIES_HEALTH_AND_FITNESS_MEDICINE",
  "PODCASTSERIES_HEALTH_AND_FITNESS_MENTAL_HEALTH",
  "PODCASTSERIES_HEALTH_AND_FITNESS_NUTRITION",
  "PODCASTSERIES_HEALTH_AND_FITNESS_SEXUALITY",
  "PODCASTSERIES_KIDS_AND_FAMILY",
  "PODCASTSERIES_KIDS_AND_FAMILY_EDUCATION_FOR_KIDS",
  "PODCASTSERIES_KIDS_AND_FAMILY_PARENTING",
  "PODCASTSERIES_KIDS_AND_FAMILY_PETS_AND_ANIMALS",
  "PODCASTSERIES_KIDS_AND_FAMILY_STORIES_FOR_KIDS",
  "PODCASTSERIES_LEISURE",
  "PODCASTSERIES_LEISURE_ANIMATION_AND_MANGA",
  "PODCASTSERIES_LEISURE_AUTOMOTIVE",
  "PODCASTSERIES_LEISURE_AVIATION",
  "PODCASTSERIES_LEISURE_CRAFTS",
  "PODCASTSERIES_LEISURE_GAMES",
  "PODCASTSERIES_LEISURE_HOBBIES",
  "PODCASTSERIES_LEISURE_HOME_AND_GARDEN",
  "PODCASTSERIES_LEISURE_VIDEO_GAMES",
  "PODCASTSERIES_MUSIC",
  "PODCASTSERIES_MUSIC_COMMENTARY",
  "PODCASTSERIES_MUSIC_HISTORY",
  "PODCASTSERIES_MUSIC_INTERVIEWS",
  "PODCASTSERIES_NEWS",
  "PODCASTSERIES_NEWS_BUSINESS",
  "PODCASTSERIES_NEWS_DAILY_NEWS",
  "PODCASTSERIES_NEWS_ENTERTAINMENT",
  "PODCASTSERIES_NEWS_COMMENTARY",
  "PODCASTSERIES_NEWS_POLITICS",
  "PODCASTSERIES_NEWS_SPORTS",
  "PODCASTSERIES_NEWS_TECH",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_BUDDHISM",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_CHRISTIANITY",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_HINDUISM",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_ISLAM",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_JUDAISM",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_RELIGION",
  "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_SPIRITUALITY",
  "PODCASTSERIES_SCIENCE",
  "PODCASTSERIES_SCIENCE_ASTRONOMY",
  "PODCASTSERIES_SCIENCE_CHEMISTRY",
  "PODCASTSERIES_SCIENCE_EARTH_SCIENCES",
  "PODCASTSERIES_SCIENCE_LIFE_SCIENCES",
  "PODCASTSERIES_SCIENCE_MATHEMATICS",
  "PODCASTSERIES_SCIENCE_NATURAL_SCIENCES",
  "PODCASTSERIES_SCIENCE_NATURE",
  "PODCASTSERIES_SCIENCE_PHYSICS",
  "PODCASTSERIES_SCIENCE_SOCIAL_SCIENCES",
  "PODCASTSERIES_SOCIETY_AND_CULTURE",
  "PODCASTSERIES_SOCIETY_AND_CULTURE_DOCUMENTARY",
  "PODCASTSERIES_SOCIETY_AND_CULTURE_PERSONAL_JOURNALS",
  "PODCASTSERIES_SOCIETY_AND_CULTURE_PHILOSOPHY",
  "PODCASTSERIES_SOCIETY_AND_CULTURE_PLACES_AND_TRAVEL",
  "PODCASTSERIES_SOCIETY_AND_CULTURE_RELATIONSHIPS",
  "PODCASTSERIES_SPORTS",
  "PODCASTSERIES_SPORTS_BASEBALL",
  "PODCASTSERIES_SPORTS_BASKETBALL",
  "PODCASTSERIES_SPORTS_CRICKET",
  "PODCASTSERIES_SPORTS_FANTASY_SPORTS",
  "PODCASTSERIES_SPORTS_FOOTBALL",
  "PODCASTSERIES_SPORTS_GOLF",
  "PODCASTSERIES_SPORTS_HOCKEY",
  "PODCASTSERIES_SPORTS_RUGBY",
  "PODCASTSERIES_SPORTS_RUNNING",
  "PODCASTSERIES_SPORTS_SOCCER",
  "PODCASTSERIES_SPORTS_SWIMMING",
  "PODCASTSERIES_SPORTS_TENNIS",
  "PODCASTSERIES_SPORTS_VOLLEYBALL",
  "PODCASTSERIES_SPORTS_WILDERNESS",
  "PODCASTSERIES_SPORTS_WRESTLING",
  "PODCASTSERIES_TECHNOLOGY",
  "PODCASTSERIES_TRUE_CRIME",
  "PODCASTSERIES_TV_AND_FILM",
  "PODCASTSERIES_TV_AND_FILM_AFTER_SHOWS",
  "PODCASTSERIES_TV_AND_FILM_HISTORY",
  "PODCASTSERIES_TV_AND_FILM_INTERVIEWS",
  "PODCASTSERIES_TV_AND_FILM_FILM_REVIEWS",
  "PODCASTSERIES_TV_AND_FILM_TV_REVIEWS",
];

export const genresName: string[] = [
  "Arts",
  "Arts Books",
  "Arts Design",
  "Arts Fashion and Beauty",
  "Arts Food",
  "Arts Performing Arts",
  "Arts Visual Arts",
  "Business",
  "Business Careers",
  "Business Entrepreneurship",
  "Business Investing",
  "Business Management",
  "Business Marketing",
  "Business Non Profit",
  "Comedy",
  "Comedy Interviews",
  "Comedy Improv",
  "Comedy Standup",
  "Education",
  "Education Courses",
  "Education How To",
  "Education Language Learning",
  "Education Self Improvement",
  "Fiction",
  "Fiction Comedy Fiction",
  "Fiction Drama",
  "Fiction Science Fiction",
  "Government",
  "History",
  "Health and Fitness",
  "Health and Fitness Alternative Health",
  "Health and Fitness Fitness",
  "Health and Fitness Medicine",
  "Health and Fitness Mental Health",
  "Health and Fitness Nutrition",
  "Health and Fitness Sexuality",
  "Kids and Family",
  "Kids and Family Education for Kids",
  "Kids and Family Parenting",
  "Kids and Family Pets and Animals",
  "Kids and Family Stories for Kids",
  "Leisure",
  "Leisure Animation and Manga",
  "Leisure Automotive",
  "Leisure Aviation",
  "Leisure Crafts",
  "Leisure Games",
  "Leisure Hobbies",
  "Leisure Home and Garden",
  "Leisure Video Games",
  "Music",
  "Music Commentary",
  "Music History",
  "Music Interviews",
  "News",
  "News Business",
  "News Daily News",
  "News Entertainment",
  "News Commentary",
  "News Politics",
  "News Sports",
  "News Tech",
  "Religion and Spirituality",
  "Religion and Spirituality Buddhism",
  "Religion and Spirituality Christianity",
  "Religion and Spirituality Hinduism",
  "Religion and Spirituality Islam",
  "Religion and Spirituality Judaism",
  "Religion and Spirituality Religion",
  "Religion and Spirituality Spirituality",
  "Science",
  "Science Astronomy",
  "Science Chemistry",
  "Science Earth Sciences",
  "Science Life Sciences",
  "Science Mathematics",
  "Science Natural Sciences",
  "Science Nature",
  "Science Physics",
  "Science Social Sciences",
  "Society and Culture",
  "Society and Culture Documentary",
  "Society and Culture Personal Journals",
  "Society and Culture Philosophy",
  "Society and Culture Places and Travel",
  "Society and Culture Relationships",
  "Sports",
  "Sports Baseball",
  "Sports Basketball",
  "Sports Cricket",
  "Sports Fantasy Sports",
  "Sports Football",
  "Sports Golf",
  "Sports Hockey",
  "Sports Rugby",
  "Sports Running",
  "Sports Soccer",
  "Sports Swimming",
  "Sports Tennis",
  "Sports Volleyball",
  "Sports Wilderness",
  "Sports Wrestling",
  "Technology",
  "True Crime",
  "TV and Film",
  "TV and Film After Shows",
  "TV and Film History",
  "TV and Film Interviews",
  "TV and Film Film Reviews",
  "TV and Film TV Reviews",
];

export const popularGenres: string[] = [
  "PODCASTSERIES_COMEDY",
  "PODCASTSERIES_NEWS",
  "PODCASTSERIES_TRUE_CRIME",
  "PODCASTSERIES_SOCIETY_AND_CULTURE",
  "PODCASTSERIES_BUSINESS",
  "PODCASTSERIES_HEALTH_AND_FITNESS",
  "PODCASTSERIES_EDUCATION",
  "PODCASTSERIES_TV_AND_FILM",
  "PODCASTSERIES_TECHNOLOGY",
  "PODCASTSERIES_SPORTS",
];
